### ISSUE TITLE
CI failure after merging master into 2018-10 integration

### ISSUE THREAD

**Issue by kg** [mono/monodevelop#6567]
https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2186536&view=logs

I merged vsfm master into 2018-10 to fix an issue with a missing nuget repository but now the build is failing with a new error:

```
2018-11-06T22:25:49.0874870Z   EmulatorSupport/XamarinDeviceManager/DeviceManagerAboutInformation.cs(26,52): error CS0117: 'AppInfo' does not contain a definition for 'AppVersion' [..../MonoDevelop.MonoDroid.csproj]
2018-11-06T22:25:49.0876030Z   EmulatorSupport/XamarinDeviceManager/DeviceManagerAboutInformation.cs(27,37): error CS0117: 'AppInfo' does not contain a definition for 'AppVersionInfo' [.../MonoDevelop.MonoDroid.csproj]
```

**Comment by Therzok** [comment]
Probably needs another merge/bump of a dep.

**Comment by mrward** [comment]
This has been fixed in latest md-addins master. md-addins PR 3824
