### ISSUE TITLE
Building on Ubuntu Linux 18.04

### ISSUE THREAD

**Issue by Commaster** [mono/monodevelop#8006]
Since the latest Monodevelop version in the Mono repository is 7.8.2.2 and nobody is pushing Monodevelop 8 I wanted to "update" manually by following the "Build from Git" instructions for Linux:
`git clone --recursive --recurse-submodules -b master --depth=1 https://github.com/mono/monodevelop -j4 && cd monodevelop && ./configure --enable-release --profile=gnome && make`
But it fails spectacularly once it tries to start building after all the Nugets:
```
Building ./Main.sln
ok=:; msbuild /verbosity:minimal /nologo /property:CodePage=65001 /property:RestorePackages=false /property:DownloadPaket=false /bl:MonoDevelop.binlog ./Main.sln /property:Configuration=ReleaseGnome || ok=false; echo @MonkeyWrench: AddFile: $(pwd)/MonoDevelop.binlog; $ok
/usr/lib/mono/msbuild/15.0/bin/MSBuild.dll /nologo /bl:MonoDevelop.binlog /property:CodePage=65001 /property:RestorePackages=false /property:DownloadPaket=false /property:Configuration=ReleaseGnome /verbosity:minimal ./Main.sln
.../monodevelop/main/Main.sln.metaproj : warning MSB4121: The project configuration for project "Xamarin.PropertyEditing" was not specified in the solution file for the solution configuration "ReleaseGnome|Any CPU". [.../monodevelop/main/Main.sln]
.../monodevelop/main/Main.sln.metaproj : warning MSB4121: The project configuration for project "Xamarin.PropertyEditing.Mac" was not specified in the solution file for the solution configuration "ReleaseGnome|Any CPU". [./monodevelop/main/Main.sln]
  MDBuildTasks -> .../monodevelop/main/msbuild/MDBuildTasks/bin/MDBuildTasks.dll
IStandardClassificationService.cs(6,34): error CS0234: The type or namespace name 'Text' does not exist in the namespace 'Microsoft.VisualStudio' (are you missing an assembly reference?) [.../monodevelop/main/external/vs-editor-api/src/Editor/Language/Def/StandardClassification/StandardClassification.csproj]
IStandardClassificationService.cs(19,9): error CS0246: The type or namespace name 'IClassificationType' could not be found (are you missing a using directive or an assembly reference?) [.../monodevelop/main/external/vs-editor-api/src/Editor/Language/Def/StandardClassification/StandardClassification.csproj]
IStandardClassificationService.cs(24,9): error CS0246: The type or namespace name 'IClassificationType' could not be found (are you missing a using directive or an assembly reference?) [.../monodevelop/main/external/vs-editor-api/src/Editor/Language/Def/StandardClassification/StandardClassification.csproj]
...
...
```

Used software:
```
dotnet-sdk-2.2 2.2.300-1
dotnet-host 2.2.5-1
msbuild 1:16.0+xamarinxplat.2019.03.13.11.00-0xamarin9+ubuntu1804b1
mono-complete 6.0.0.302-0xamarin3+ubuntu1804b1
```

Can you update the build instructions? Or fix the repository? Or push Monodevelop 8 to the Mono repository?

**Comment by knuxbbs** [comment]
Look like here nobody cares about Linux users. I think that this repo should be renamed for 'Visual Studio for Mac' only.

**Comment by netonjm** [comment]
@abock cc

**Comment by lextm** [comment]
You are supposed to build 8.1 branch (which I have partial success on Windows). I have a Travis CI build script for 7.8 branch, but I think it should also work for 8.1 branch.

**Comment by Commaster** [comment]
@lextm sorry, but I did try build all 8.something branches before submitting this issue. And as you can understand 7.8 is irrelevant (since that's what we have in the Mono Repository)

**Comment by Commaster** [comment]
stable mono branch just updated msbuild. Now Monodevelop 7.8.2 is unable to build at all. Please fix ASAP

**Comment by knocte** [comment]
> 7.8.4.2 seems to work with msbuild 16.1. Phew.

What version of mono brings msbuild 16.1? can you share your build script? how do you get 7.8.4.2?

**Comment by Commaster** [comment]
@knocte I'm on the preview-\<ubuntuversion\> branch most of the time. Monodevelop 7.8.4.2 just popped up one day and still works fine with Mono 6.4 and msbuild 16.3.
```
Build Information
Release ID: 708040002
Git revision: 622db12503514afdb641c31615408bfe905a7312
Build date: 2019-07-17 17:02:07-04
```
I was unable to locate this commit though.

I will continue retrying to build Monodevelop 8.x every weekend until it succeeds.

**Comment by Commaster** [comment]
Two and a half months later... Still no improvements.

**Comment by CommanderStrax** [comment]
I'm on Arch. I tried building the release-8.4 branch and the release-7.8 branch. Neither of them is buildable.

8.4 gives me an exception on make ```>>>> xbuild tool is deprecated and will be removed in future updates, use msbuild instead <<<<

MSBUILD: error MSBUILD0004: Too many project files specified
```

and yes, MSBuild is installed (`dotnet build` is working)

while 7.8 failed on downloading a bunch of files, for example
`https://www.myget.org/F/azure-appservice/api/v3/flatcontainer/microsoft.visualstudio.coreutility/15.8.519/microsoft.visualstudio.coreutility.15.8.519.nupkg`

Is this project dead? Cause I can also not find any changelogs or just a 'normal' binary tarball.

**Comment by knocte** [comment]
> I'm on Arch

That's even more difficult to pull off, AFAIU, because Arch might not have packages of msbuild yet, and xbuild might be too buggy to be able to build monodevelop at this point.

**Comment by CommanderStrax** [comment]
xbuild is unable to build it,. The 'Too many project files specified' comes from xbuild. However, I have msbuild installed. 

As for msbuild, unless I'm mistaken it is part of the normal package repository.

```
dotnet build
Microsoft (R) Build Engine version 15.9.20.63311 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.
```

Link to installed package: https://www.archlinux.org/packages/community/x86_64/dotnet-sdk/

**Comment by lextm** [comment]
@CommanderStrax MSBuild engine for .NET Core is likely to fail, as usually you need to use MSBuild for Mono,
```
➜  ~ msbuild
Microsoft (R) Build Engine version 16.1.85+gad9c9926a7 for Mono
Copyright (C) Microsoft Corporation. All rights reserved.
```

**Comment by CommanderStrax** [comment]
ohh, that makes more sense. That might also explain why the autodiscover didn't find it.

**Comment by aabc123** [comment]
Has anyone managed to get 8.x to build on Linux yet?  I'm having similar issues building on Ubuntu 19.10.  We use VS Mac 8 and share projects with Linux so need to use a more up-to-date version on Linux.

**Comment by CommanderStrax** [comment]
@aabc123 nope. Guess Microsoft getting Xamarin wasn't a good thing for us Linux people. Currently the only proper C# IDE would be ReSharper's Rider which isn't free nor open-source but at least works.

**Comment by Commaster** [comment]
It's Monodelop 8.6 already, and Mono 6.6.

And this is **STILL** broken.

**Comment by akihikodaki** [comment]
I was working to make MonoDevelop run on Linux again but have failed.

Apparently the easiest way is to remove code in `main/external/vs-editor-api` depending on macOS or modify it to work on GTK/Linux. Additionally, you have to remove dependencies on the binary specific to macOS included in Visual Studio for macOS, which I failed. You cannot remove `MonoDevelop.TextEditor`, the addin containing "the new text editor" because it provides user preference information. MonoDevelop's addin mechanism and MEF makes difficult to track dependencies. Once you get it work without the new text editor, it should not be difficult to modify it to run on Linux.

The dependency on the new text editor is a challenge for those who builds MonoDevelop also for macOS or Windows, and don't want to be bothered to copy a binary from Visual Studio maybe because they don't want to use code not open-source, or just because it is trobulesome. (See #8289.)

**Comment by CommanderStrax** [comment]
oh. Great. Welp, good thing I didn't waste any time on chasing down that msbuild problem I had further up the comments.

**Comment by Commaster** [comment]
`Find/FindCommandArgs.cs(8,43): error CS0246: The type or namespace name 'EditorCommandArgs' could not be found (are you missing a using directive or an assembly reference?) [.../monodevelop/main/external/vs-editor-api/src/Editor/Text/Def/Extras/Extras.csproj]`

`IStandardClassificationService.cs(6,34): error CS0234: The type or namespace name 'Text' does not exist in the namespace 'Microsoft.VisualStudio' (are you missing an assembly reference?) [.../monodevelop/main/external/vs-editor-api/src/Editor/Language/Def/StandardClassification/StandardClassification.csproj]`

`AllLowerCamelCaseMatcher.cs(7,46): error CS0234: The type or namespace name 'Span' does not exist in the namespace 'Microsoft.VisualStudio.Text' (are you missing an assembly reference?) [.../monodevelop/main/external/vs-editor-api/src/Editor/Text/Impl/PatternMatching/PatternMatchingImpl.csproj]`

**Comment by Commaster** [comment]
The main question would be:
 Why does --enablegnomeplatform depends on a Mac-exclusive vs-editor-api project?!

**Comment by pikachuk** [comment]
This repo really seems dead

**Comment by pikachuk** [comment]
I've btw seen a post on the topic that could explain why we can't build it 
![image](https://user-images.githubusercontent.com/16335601/70079376-ea9c1800-1604-11ea-8ffe-49984b7bc16a.png)

**Comment by lextm** [comment]
@pikachuk Thanks for quoting my blog post. I plan to give it an update based on recent new facts.

Thera are still outstanding issues to build MonoDevelop on Windows/Linux, but Microsoft did open source more of its relevant code.

**Comment by pikachuk** [comment]
Oh I see, that's good then.
I hope we'll have a way to do it soon, since as we still don't have an official visual studio for Linux, Monodevelop is the only real solution for a native C# development experience on Linux (except rider but it isn't free and for me the demo has some issues building the template projects)

**Comment by Commaster** [comment]
There have been some major improvements, I only get 61 errors instead of the usual 120-ish. Could be due to the dotnet 3.1 update :man_shrugging: 

Used software:

```
dotnet-sdk-3.1 3.1.100-1
dotnet-host 3.1.0-1
msbuild 1:16.4+xamarinxplat.2019.09.09.15.03-0xamarin5+ubuntu1804b1
mono-complete 6.6.0.161-0xamarin5+ubuntu1804b1
```

Current issue:
```
".../monodevelop/main/Main.sln" (default target) (1) ->
".../monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Core.csproj.metaproj" (default target) (2) ->
".../monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Core.csproj" (default target) (4) ->
".../monodevelop/main/external/vs-editor-api/src/Editor/Language/Def/StandardClassification/StandardClassification.csproj" (default target) (13:2) ->
(CoreCompile target) -> 
IStandardClassificationService.cs ...
(6,34): error CS0234: The type or namespace name 'Text' does not exist in the namespace 'Microsoft.VisualStudio' (are you missing an assembly reference?) [.../monodevelop/main/external/vs-editor-api/src/Editor/Language/Def/StandardClassification/StandardClassification.csproj]
(19,9):, (24,9):, (29,9):, (34,9):, (39,9):, (44,9):, (49,9):, (54,9):, (59,9):, (64,9):, (69,9):, (74,9):, (79,9):, (84,9):, (89,9):, (94,9):
        error CS0246: The type or namespace name 'IClassificationType' could not be found (are you missing a using directive or an assembly reference?) [.../monodevelop/main/external/vs-editor-api/src/Editor/Language/Def/StandardClassification/StandardClassification.csproj]


".../monodevelop/main/Main.sln" (default target) (1) ->
".../monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Core.csproj.metaproj" (default target) (2) ->
".../monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Core.csproj" (default target) (4) ->
".../monodevelop/main/external/vs-editor-api/src/Editor/Text/Impl/PatternMatching/PatternMatchingImpl.csproj" (default target) (36:2) ->
  AllLowerCamelCaseMatcher.cs(7,46):, ArraySlice.cs(5,46):, CamelCaseResult.cs(5,46):, PatternMatcher.cs(10,46):, SimplePatternMatcher.cs(6,46):, StringBreaker.cs(7,46):, PatternMatchExtensions.cs(8,39):, PatternMatcher.cs(306,32):
        error CS0234: The type or namespace name 'Span' does not exist in the namespace 'Microsoft.VisualStudio.Text' (are you missing an assembly reference?) [.../monodevelop/main/external/vs-editor-api/src/Editor/Text/Impl/PatternMatching/PatternMatchingImpl.csproj]
  PatternMatcherFactory.cs(4,58):
        error CS0234: The type or namespace name 'PatternMatcherCreationFlags' does not exist in the namespace 'Microsoft.VisualStudio.Text.PatternMatching' (are you missing an assembly reference?) [.../monodevelop/main/external/vs-editor-api/src/Editor/Text/Impl/PatternMatching/PatternMatchingImpl.csproj]
  PatternMatcher.cs(21,67):, PatternMatcherFactory.cs(11,16):
        error CS0246: The type or namespace name 'IPatternMatcher' could not be found (are you missing a using directive or an assembly reference?) [.../monodevelop/main/external/vs-editor-api/src/Editor/Text/Impl/PatternMatching/PatternMatchingImpl.csproj]
  PatternMatcherFactory.cs(9,42):
        error CS0246: The type or namespace name 'IPatternMatcherFactory2' could not be found (are you missing a using directive or an assembly reference?) [.../monodevelop/main/external/vs-editor-api/src/Editor/Text/Impl/PatternMatching/PatternMatchingImpl.csproj]
  PatternMatcherFactory.cs(8,20):
        error CS0246: The type or namespace name 'IPatternMatcherFactory' could not be found (are you missing a using directive or an assembly reference?) [.../monodevelop/main/external/vs-editor-api/src/Editor/Text/Impl/PatternMatching/PatternMatchingImpl.csproj]
  PatternMatcherFactory.cs(11,69):, PatternMatcherFactory.cs(17,69):
        error CS0246: The type or namespace name 'PatternMatcherCreationOptions' could not be found (are you missing a using directive or an assembly reference?) [.../monodevelop/main/external/vs-editor-api/src/Editor/Text/Impl/PatternMatching/PatternMatchingImpl.csproj]
  PatternMatcherFactory.cs(17,116):, PatternMatcherFactory.cs(17,16):
        error CS0246: The type or namespace name 'IPatternMatcher' could not be found (are you missing a using directive or an assembly reference?) [.../monodevelop/main/external/vs-editor-api/src/Editor/Text/Impl/PatternMatching/PatternMatchingImpl.csproj]
  StringBreaker.cs(75,24):
        error CS0246: The type or namespace name 'ArrayBuilder<>' could not be found (are you missing a using directive or an assembly reference?) [.../monodevelop/main/external/vs-editor-api/src/Editor/Text/Impl/PatternMatching/PatternMatchingImpl.csproj]
  StringBreaker.cs(102,30):, StringBreaker.cs(20,26):, CamelCaseResult.cs(17,29):, CamelCaseResult.cs(20,97):
        error CS0246: The type or namespace name 'ArrayBuilder<>' could not be found (are you missing a using directive or an assembly reference?) [.../monodevelop/main/external/vs-editor-api/src/Editor/Text/Impl/PatternMatching/PatternMatchingImpl.csproj]
  PatternMatchExtensions.cs(44,57):, PatternMatchExtensions.cs(44,81):, PatternMatchExtensions.cs(44,24):, CamelCaseResult.cs(50,24):, PatternMatcher.cs(509,17):, PatternMatcher.cs(520,17):, AllLowerCamelCaseMatcher.cs(41,20):, AllLowerCamelCaseMatcher.cs(68,28):
        error CS0246: The type or namespace name 'PatternMatchKind' could not be found (are you missing a using directive or an assembly reference?) [.../monodevelop/main/external/vs-editor-api/src/Editor/Text/Impl/PatternMatching/PatternMatchingImpl.csproj]
  PatternMatchExtensions.cs(8,56):, PatternMatchExtensions.cs(8,77):, PatternMatchExtensions.cs(18,47):, PatternMatchExtensions.cs(18,68):, PatternMatchExtensions.cs(18,23):, PatternMatcher.cs(125,25):, PatternMatcher.cs(152,17):, PatternMatcher.cs(164,24):, PatternMatcher.cs(178,17):, PatternMatcher.cs(337,17):, PatternMatcher.cs(462,17):, ContainerPatternMatcher.cs(57,29):, ContainerPatternMatcher.cs(73,21):, SimplePatternMatcher.cs(43,29):
        error CS0246: The type or namespace name 'PatternMatch' could not be found (are you missing a using directive or an assembly reference?) [.../monodevelop/main/external/vs-editor-api/src/Editor/Text/Impl/PatternMatching/PatternMatchingImpl.csproj]
```

`2019-12-09 07:11:38+01`: `531869741e5cb3a3d336a0e81395c36dd72aa4b6` Same issue

**Comment by hardhub** [comment]
I also cannot build it on Windows:

```
"D:\Products\MonoDevelop\main\Main.sln" (default target) (1:2) ->
"D:\Products\MonoDevelop\main\src\core\MonoDevelop.Ide\MonoDevelop.Ide.csproj" (default target) (14:61) ->
(CoreCompile target) ->
  MonoDevelop.Components.Commands\CommandManager.cs(515,8): error CS0103: The name 'currentEvent' does not exist in the current context [D:\Products\MonoDevelop\main\src\core\MonoDevelop.Ide\MonoDevelop.Ide.csproj]
  MonoDevelop.Components.Commands\CommandManager.cs(516,5): error CS0103: The name 'currentEvent' does not exist in the current context [D:\Products\MonoDevelop\main\src\core\MonoDevelop.Ide\MonoDevelop.Ide.csproj]
  MonoDevelop.Components.Commands\CommandManager.cs(516,26): error CS0103: The name 'AppKit' does not exist in the current context [D:\Products\MonoDevelop\main\src\core\MonoDevelop.Ide\MonoDevelop.Ide.csproj]
  MonoDevelop.Components.Commands\CommandManager.cs(517,5): error CS0103: The name 'firstResponder' does not exist in the current context [D:\Products\MonoDevelop\main\src\core\MonoDevelop.Ide\MonoDevelop.Ide.csproj]
  MonoDevelop.Components.Commands\CommandManager.cs(517,23): error CS0246: The type or namespace name 'AppKit' could not be found (are you missing a using directive or an assembly reference?) [D:\Products\MonoDevelop\main\src\core\M
onoDevelop.Ide\MonoDevelop.Ide.csproj]
  MonoDevelop.Components.Commands\CommandManager.cs(518,13): error CS0103: The name 'window' does not exist in the current context [D:\Products\MonoDevelop\main\src\core\MonoDevelop.Ide\MonoDevelop.Ide.csproj]
  MonoDevelop.Components.Commands\CommandManager.cs(520,17): error CS0103: The name 'currentEvent' does not exist in the current context [D:\Products\MonoDevelop\main\src\core\MonoDevelop.Ide\MonoDevelop.Ide.csproj]
  MonoDevelop.Components.Commands\CommandManager.cs(521,5): error CS0103: The name 'SimulateViewKeyActionBehaviour' does not exist in the current context [D:\Products\MonoDevelop\main\src\core\MonoDevelop.Ide\MonoDevelop.Ide.csproj]
  MonoDevelop.Components.Commands\CommandManager.cs(521,43): error CS0103: The name 'currentEvent' does not exist in the current context [D:\Products\MonoDevelop\main\src\core\MonoDevelop.Ide\MonoDevelop.Ide.csproj]
  MonoDevelop.Components.Commands\CommandManager.cs(522,5): error CS0103: The name 'retVal' does not exist in the current context [D:\Products\MonoDevelop\main\src\core\MonoDevelop.Ide\MonoDevelop.Ide.csproj]
  MonoDevelop.Components.Commands\CommandManager.cs(530,15): error CS0103: The name 'retVal' does not exist in the current context [D:\Products\MonoDevelop\main\src\core\MonoDevelop.Ide\MonoDevelop.Ide.csproj]
  MonoDevelop.Components.Commands\CommandManager.cs(2429,32): error CS0246: The type or namespace name 'AppKit' could not be found (are you missing a using directive or an assembly reference?) [D:\Products\MonoDevelop\main\src\core\
MonoDevelop.Ide\MonoDevelop.Ide.csproj]
  MonoDevelop.Components.Commands\CommandManager.cs(2430,14): error CS0103: The name 'Mac' does not exist in the current context [D:\Products\MonoDevelop\main\src\core\MonoDevelop.Ide\MonoDevelop.Ide.csproj]
  MonoDevelop.Ide.Updater\AddinsUpdateHandler.cs(107,109): error CS0246: The type or namespace name 'AppKit' could not be found (are you missing a using directive or an assembly reference?) [D:\Products\MonoDevelop\main\src\core\Mon
oDevelop.Ide\MonoDevelop.Ide.csproj]
  MonoDevelop.Ide.Updater\AddinsUpdateHandler.cs(114,26): error CS0234: The type or namespace name 'Mac' does not exist in the namespace 'MonoDevelop.Components' (are you missing an assembly reference?) [D:\Products\MonoDevelop\main
\src\core\MonoDevelop.Ide\MonoDevelop.Ide.csproj]
  MonoDevelop.Ide.Updater\AddinsUpdateHandler.cs(116,52): error CS0103: The name 'AppKit' does not exist in the current context [D:\Products\MonoDevelop\main\src\core\MonoDevelop.Ide\MonoDevelop.Ide.csproj]
```

**Comment by hardhub** [comment]
> This repo really seems dead

"Embrace, extend, and extinguish" (EEE)

**Comment by lextm** [comment]
@hardhub You have to remove all **Mac** related projects from the solution and then compile (there are other changes needed), but even if you somehow get it compiled, other issues (like no way to set break points) remain (last time I tried).

**Comment by scherenhaenden** [comment]
If that is open source. It is not possible to just fork it? and create a different version that is not depending on main source? or it is legally gray?

**Comment by lextm** [comment]
@scherenhaenden You can of course create your fork (and legally).

The barrier here is how to fully understand each of the components, and (in most cases) the various dependencies. It is just too luxury to spend time on a huge project like this, when 8.x introduces too many gaps.

**Comment by scherenhaenden** [comment]
@lextm 

It seems like indeed Monodevelop is just not more usable for future Projects... if it is so, maybe we should considere to use rider or other languages...

**Comment by pikachuk** [comment]
There is an other open source project named Consulo that is a fork of Intellij IDEA Community adding support for C#.
I feel like it's a good free open source alternative to rider.
https://github.com/consulo/consulo

**Comment by Commaster** [comment]
I have both Rider and Consulo. Still prefer Monodevelop :man_shrugging:

**Comment by scherenhaenden** [comment]
I have Rider... I need my Workspaces back -.-

**Comment by scherenhaenden** [comment]
I'm gonna take a look onto that Consulo thing

**Comment by scherenhaenden** [comment]
I tested Consulo. somehow good but not quite there.

I need workspaces, Rider does not even know what that is

**Comment by enderger** [comment]
Can we not fork the 7 branch?

**Comment by scherenhaenden** [comment]
that would be great. The thing is that it might not be enough ppl there to work for a that fork, either because the knowledge is not quite enough or because there is not enough quorum

**Comment by lextm** [comment]
You can fork in any way you like, but keep in mind,

* 7.x branch is years old, so it might not work with latest (such as .NET Core 3.x).
* 8.x branch focused too much on macOS, so you probably won't be able to compile it on Windows/Linux. The typical issues have been discussed above, or in the Gitter channel.

If you really want to contribute, make use of all previous knowledge, or you probably have no clue where to get started on this huge project.

**Comment by hardhub** [comment]
@lextm is it possible to move changes made in 8 branch to 7 branch?
I mean something to support such things as .NET Core 3.x

It looks like MS bought Xamarin and ruined it and now new "Mono" is needed

But I agree with @scherenhaenden 

> that it might not be enough ppl there to work for a that fork

In any case it does not mean that we should not discuss it.   
But it is very strange that we are doing it on Github which is owned by MS.  
I have some doubts regarding that.

**Comment by scherenhaenden** [comment]
@hardhub It could be great if we make a full quorum about it and even better if we could get enough ppl to work onto a fork. 

But I see it on myself, right now, work, kids, helth and everything in between is eroding my free time... I cannot ask ppl to work on a project like that when I'm not offering my self at least some lines of code every week.

**Comment by clcrutch** [comment]
I'm interested in participating, maybe even leading the fork for the time being.  I started a conversation on Reddit, chime in below and let's see if we can reach a quorum.

https://www.reddit.com/r/dotnet/comments/ffsgcw/fork_monodevelop_for_better_linux_support/

**Comment by clcrutch** [comment]
@hardhub @scherenhaenden I'd be interested in helping with/starting a fork.  Do we want to start like a Slack chat/something else to try to better communicate?

**Comment by hardhub** [comment]
@clcrutch 

I am using qTox and in the future will setup own Matrix server for communications.

Though I like how @scherenhaenden described situation:

- work
- kids
- health
- etc

We need to know how much time it can take. So some roadmap for Monodevelop work is a good idea I think.

And what is about MS roadmap?  
What will do MS with MonoDevelop after merging Net Core and Net Framework into NET 5?  
Which plans do they have at all?  
What do you think guys?

**Comment by clcrutch** [comment]
My situation includes:
* work
* health
* grad school
* etc

So I absolutely understand time constraints.  Let's see if we can reason about the questions you pose:
1. I'm not really sure about this one, but given the fact that large parts of the editor code is closed source, I don't think we can expect this project to become community-driven again.
2. As it seems like the MonoDevelop repo is going all-in on macOS, I'm not sure that what MS decides to do would impact a potential fork very much.
3. While I hold out hope that MS brings out a Visual Studio for Linux, this seems unlikely as MonoDevelop would have been the best starting point and does not appear to be going in that direction.

I am willing to work on this project between school/work/family but understand it's just too much for a single or even multiple people to handle.  I'm only willing to go down this path if there is enough interest and desire from the community to drive this project forward.

**Comment by scherenhaenden** [comment]
@clcrutch @hardhub 

I would totally love to going down deeper into this matter. But like @clcrutch said, ppl might wanna get involved and even it might be at the end that a bunch of developers tried to create something awesome, but it is of the escenes for the most of us to know if we are spending out free time in the right way. Right now, I could try to give some effort, but we would need a lot of ppl. 

I think that it is possible depending on how a few things are handled and the first one is how to get enough developers involved to the possible project and the first developers got to see some results and that is the main key. when ppl see how is the development going and see that things are moving forwards and steady, things are going to work.

The other very important thing, is to show that this is needed, why ppl should get involved with and how this togethership of developers can solve other problems that they have... And ID where they can work with C#

**Comment by lextm** [comment]
@hardhub If you really want to contribute, I suggest the following,

1. Learn really good about GTK#.
1. Get familiar with the new editor from Microsoft (its Cocoa implementation for macOS is open sourced).
1. Implement a new editor based on GTK#.

Then your work plus the current 8.x code base from Microsoft should be the foundation for future MonoDevelop users.

If you do need guidance on that path, try to talk to Microsoft guys. I believe @mhutch and others are more than happy to assist you.

**Comment by knuxbbs** [comment]
Regarding GtkSharp, there is a lot of work to do. The mostly active repo [is this](https://github.com/GtkSharp/GtkSharp).

I'm working in [separating the code generator](https://github.com/glib-sharp/gapi) from the main repo. Gir is the way to go.

Contributions are welcome.

**Comment by enderger** [comment]
I have little experience with text editors in general, but have managed to get something with gtksharp working. Also, we must consider all options, as Avalonia and Eto.Forms may make a more native looking GUI.
As for dotnet core 3 integration, we may be able to build around the command line implementation.

**Comment by scherenhaenden** [comment]
Maybe we should have a little channel in slack/gitter to speak about this things.

**Comment by knocte** [comment]
> Gir is the way to go.

There was a gir-to-C# effort here too: https://github.com/glibsharp

> Maybe we should have a little channel in slack/gitter to speak about this things.

The gitter channel of monodevelop (this repo) is not used these days by MS/VS4Mac people, so we could use this.

**Comment by zubovm** [comment]
> > Gir is the way to go.
> 
> There was a gir-to-C# effort here too: https://github.com/glibsharp
> 
> > Maybe we should have a little channel in slack/gitter to speak about this things.
> 
> The gitter channel of monodevelop (this repo) is not used these days by MS/VS4Mac people, so we could use this.

Do you mean 
https://gitter.im/mono/monodevelop ? - That channel?

**Comment by knocte** [comment]
> https://gitter.im/mono/monodevelop ? - That channel?

Yes

**Comment by zubovm** [comment]
> 
> Yes

Thanks. I joined that channel, I would be glad to provide any help in monodevelop resurrection; I've also asked a question about current building state of 7.8.4.1.

**Comment by scherenhaenden** [comment]
That channel? really? does that make sense? 

I thought we would have to start a new fork

**Comment by kekekeks** [comment]
>Also, we must consider all options, as Avalonia and Eto.Forms may make a more native looking GUI.

1) There is [an Avalonia-based port](https://github.com/AvaloniaUI/AvaloniaEdit/) of [AvalonEdit](http://avalonedit.net/)
2) A full-fledged unicode layout support has been recently merged to master, introducing `Run`, `GlyphRun` and low-level text APIs

Note, that Avalonia currently uses libX11 directly, so embedding to GTK2 would require either resurrecting the old GTK2 backend or implementation of client-side XEmbed protocol and integration with GLib's event sources.

If you are serious about reviving the Linux version of MonoDevelop, I could implement one of the options and give you an example code for GTK2 integration.

**Comment by trampster** [comment]
MonoDevelop has been forked by the community in order to continue it's development here:
https://github.com/dotdevelop/dotdevelop
