### PR TITLE
Switch StressTest to NUnit packagereference

### PR DESCRIPTION
**Pull request by Therzok**

### CODE REVIEW

**Comment by mrward** [comment]
Build is failing. 

```
 MonoDevelop.StressTest/Scenarios/DefaultScenario.cs(33,23): error CS0234: The type or namespace name 'SyntaxHelpers' does not exist in the namespace 'NUnit.Framework' (are you missing an assembly reference?) 
```

Looks like the syntax helpers, such as `Has` have moved from the NUnit.Framework.SyntaxHelpers namespace to NUnit.Framework in 2.7.0.

**Comment by Therzok** [comment]
Fixed

**Comment by directhex** [comment]
Unit test failures:

```
System.NullReferenceException : Object reference not set to an instance of an object
  at MonoDevelop.Ide.TypeSystem.MonoDevelopWorkspace.GetDocument (Microsoft.CodeAnalysis.DocumentId documentId, System.Threading.CancellationToken cancellationToken) [0x00000] in /Users/vsts/agent/2.150.3/work/1/s/monodevelop/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs:1291 
  at MonoDevelop.Ide.TypeSystem.WorkspaceFilesCacheTests.TestWorkspaceFilesCacheUpdated_NetStandardProject_CSharpFileAddedExternally () [0x003a2] in /Users/vsts/agent/2.150.3/work/1/s/monodevelop/main/tests/Ide.Tests/MonoDevelop.Ide.TypeSystem/WorkspaceFilesCacheTests.cs:190 
  at MonoDevelop.Ide.TypeSystem.WorkspaceFilesCacheTests.TestWorkspaceFilesCacheUpdated_NetStandardProject_CSharpFileAddedExternally () [0x00458] in /Users/vsts/agent/2.150.3/work/1/s/monodevelop/main/tests/Ide.Tests/MonoDevelop.Ide.TypeSystem/WorkspaceFilesCacheTests.cs:193 
```

and

```
Performance regression. Baseline: 7.631, Result: 15.316 (+1.01)
```

**Comment by directhex** [comment]
Is NUnit 2.7 just slower than the previous version, causing the perf failure?

**Comment by Therzok** [comment]
No, we haven't updated the baseline for the test itself. That failure is expected.

**Comment by marek-safar** [comment]
@Therzok who can press the merge button?

**Comment by Therzok** [comment]
@slluis ^^
